//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterviewAcer.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterviewStageFeedback
    {
        public int Id { get; set; }
        public int InterviewId { get; set; }
        public int StageId { get; set; }
        public string Feedback { get; set; }
    
        public virtual InterviewDetail InterviewDetail { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
