
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InterviewAcer.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Stage
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Stage()
    {

        this.StageGroups = new HashSet<StageGroup>();

        this.InterviewCompletedStageMappings = new HashSet<InterviewCompletedStageMapping>();

    }


    public int Id { get; set; }

    public int InterviewTypeId { get; set; }

    public string StageName { get; set; }

    public int Sequence { get; set; }



    public virtual InterviewType InterviewType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<StageGroup> StageGroups { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<InterviewCompletedStageMapping> InterviewCompletedStageMappings { get; set; }

}

}
